import type { Metadata } from "next";
import { Anton, Geist, Geist_Mono, Inter, Inter_Tight, Outfit } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";
const Integrated = localFont({
  src: [
    {
      path: './fonts/Integrated.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-integrated', // Use lowercase with --font- prefix
  display: 'swap',
});

const Kudrya = localFont({
  src: [
    {
      path: './fonts/Kudryashev_Display_Extra_Contrast_Sans.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-kudryashev',
  display: 'swap',
});

const Helvetica = localFont({
  src: [
    {
      path: './fonts/HelveticaNeueLight.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/HelveticaNeueBold.otf',
      weight: '800',
      style: 'normal',
    },
  ],
  variable: '--font-helvetica', // Use lowercase with --font- prefix
  display: 'swap',
});

const ppMonument = localFont({
  src: [
    {
      path: './fonts/MonumentExtended-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    
  
  ],
  variable: '--font-pp-monument',
  display: 'swap',
});
const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const anton = Anton({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-anton",
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const inter = Inter_Tight({
  variable: "--font-Inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Build It",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${outfit.variable} ${Kudrya.variable} ${Helvetica.variable} ${inter.variable} ${anton.variable} ${Integrated.variable} ${ppMonument.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
